services:
  - type: web
    name: auction-site
    env: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn auction_site.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: auction-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

